routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CurrenciesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserPriceAlertsController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/user/settings', [UserSettings::class, 'view'])->middleware(['auth'])->name('user_settings');
Route::get('/currencies/{currency}', [CurrenciesController::class, 'view'])->middleware(['auth'])->name('currencies');
Route::get('/', [CurrenciesController::class, 'index'])->middleware(['auth'])->name('dashboard');
Route::get('/currencies/user/currencies/order', [CurrenciesController::class, 'order'])->middleware(['auth'])->name('dashboard_settings');

// AJAX Endpoints
Route::post('/currencies/user/order/update', [CurrenciesController::class, 'updateOrder'])->middleware(['auth']);
Route::post('/currencies/user/order/hide', [CurrenciesController::class, 'orderHide'])->middleware(['auth']);
Route::post('/currencies/ajax/data', [CurrenciesController::class, 'ajaxData'])->middleware(['auth']);


Route::post('/alerts/store', [UserPriceAlertsController::class, 'store'])->middleware(['auth']);
Route::post('/alerts/update', [UserPriceAlertsController::class, 'update'])->middleware(['auth']);
Route::get('/alerts/view', [UserPriceAlertsController::class, 'view'])->middleware(['auth']);
Route::get('/alerts/index', [UserPriceAlertsController::class, 'index'])->middleware(['auth'])->name('alerts');
Route::get('/alerts/create', [UserPriceAlertsController::class, 'create'])->middleware(['auth'])->name('create-alert');
Route::get('/alerts/edit/{id}', [UserPriceAlertsController::class, 'edit'])->middleware(['auth'])->name('edit-alert');
Route::post('/alerts/ajax/create', [UserPriceAlertsController::class, 'ajaxCreate'])->middleware(['auth']);

Route::middleware([isAdmin::class])->group(function () {
    Route::get('/backend/settings', [AdminController::class, 'view']);
    Route::post('/backend/settings/update', [AdminController::class, 'update']);
});



require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard/view.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Currencies') }}
        </h2>
    </x-slot>

    <div class="row">
            @foreach($data as $currency)
                <div style="padding-top:20px;" class="col-sm-4">
                    <div class="card">
                    <div class="card-header">
                        <a href="/currencies/{{ $currency['acronym'] }}">
                            <div class="row">
                                <div class="col-sm-6"><h4>{{ $currency['currency'] }}</h4></div>
                                <div class="col-sm-6"><h4>{{ $currency['acronym'] }}</h4></div>
                            </div>
                            
                        </a>
                    </div>
                        <div class="card-body">
                            <div style="height:300px;" id={{ $currency['acronym'] }}>
                                <div style="padding-top:25%; padding-left:50%">
                                    <div class="spinner-border"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-sm-6">Price</div>
                                <div class="col-sm-6">£{{ $currency['price'] }}</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">Percentage Difference</div>
                                <div class="col-sm-6">{{ $currency['percentage_diff'] }}%</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">Max Value</div>
                                <div class="col-sm-6">£{{ $currency['max_value'] }}</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">Min Value</div>
                                <div class="col-sm-6">£{{ $currency['min_value'] }}</div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">Mean Value</div>
                                <div class="col-sm-6">£{{ $currency['mean_value'] }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
    </div>

    <script>
        var json_data = {!! $json_data !!};
    </script>
    @push('scripts')
        <script src="js/dashboard2.js"></script>
    @endpush

</x-app-layout>